### ISSUE TITLE
`id`，`title`，`ruby` のミスマッチが起きている項目が存在する

### ISSUE THREAD

**Issue by builtinnya** [anilogia/animedb#20]
ref: https://github.com/anilogia/animedb/pull/19#issuecomment-260323897 by @haruyama 

>* ANS000452200 
>    * id: ギャラクシーエンジェル(第3期) / title: ギャラクシーエンジェル / ruby: ギャラクシーエンジェルエース ／ ギャラクシーエンジェルダブルエース(変更前)
>    * ruby は ギャラクシーエンジェルダブルエース としました. id や title も ギャラクシーエンジェルAA にするのが適当かもしれません
>
>* ANS000156600
>    * id: アルフレッド・J・クワックの冒険 / title: アルフレッド・J・クワックの冒険 / ruby: チイサナアヒルノオオキナアイノモノガタリ アヒルノクワック
>    * [小さなアヒルの大きな愛の物語 あひるのクワック - Wikipedia](https://ja.wikipedia.org/wiki/%E5%B0%8F%E3%81%95%E3%81%AA%E3%82%A2%E3%83%92%E3%83%AB%E3%81%AE%E5%A4%A7%E3%81%8D%E3%81%AA%E6%84%9B%E3%81%AE%E7%89%A9%E8%AA%9E_%E3%81%82%E3%81%B2%E3%82%8B%E3%81%AE%E3%82%AF%E3%83%AF%E3%83%83%E3%82%AF)
>        * id, title を修正するのが適当かもしれません
>
>* ANS000806400 
>    * id: みなしごハッチ ママにだかれて / title: みなしごハッチ ママにだかれて / ruby: コンチュウモノガタリ ミナシゴハッチ ママニダカレテ
>    * id, title, ruby で統一すべき?
>
>* ANS000604400
>    * id: それいけ!アンパンマン おともだちシリーズ/ファンタジー / title: それいけ!アンパンマン おともだちシリーズ/ファンタジー/ ruby: ソレイケアンパンマン オトモダチシリーズ ファンタジー バタコサントソラトブマフラー
>    * [おいでよ！アンパンマン沼　バタコさんと空飛ぶマフラー](http://sorean.blog.fc2.com/blog-entry-865.html) アンパンまんの中の一話のようです. ruby にだけ バタコサントソラトブマフラー の情報があるので id, title に反映させたほうがいいかもしれません
>
>* ANS008051700
>    * id: ガリレイドンナ / title: ガリレイドンナ / ruby: ガリレイドンナ Storia di tre sorelle a caccia di un mistero (変更前)
>    * Storia 以下はタイトルに含めなくてよいのではないかと思い ruby も ガリレイドンナ のみにしています

**Comment by builtinnya** [comment]
ギャラクシーエンジェルに関しては，現状のまま「ギャラクシーエンジェル(第3期)」
ref: https://github.com/anilogia/animedb/pull/19#issuecomment-260327012

**Comment by honeshabri** [comment]
> ガリレイドンナ  

rubyも「ガリレイドンナ」のみでいいです

**Comment by honeshabri** [comment]
> 小さなアヒルの大きな愛の物語 あひるのクワック  

id,title共に『あひるのクワック』とします
rubyは「アヒルノクワック」です

根拠としては『アニメ作品事典』や主題歌CDでは『あひるのクワック』となっているからです
「小さなアヒルの~」は『ガリレイドンナ』の「Storia~」と同じようなものだと判断しました

**Comment by honeshabri** [comment]
> みなしごハッチ

「昆虫物語」は必要
『アニメ作品事典』ではシリーズ全てに「昆虫物語」が付いている
amazonの商品名でも「昆虫物語」ありの商品が多い

**Comment by honeshabri** [comment]
> それいけ!アンパンマン おともだちシリーズ/ファンタジー

title,idを`それいけ!アンパンマン おともだちシリーズ/ファンタジー「バタコさんと空飛ぶマフラー」`とする
rubyは`ソレイケアンパンマン オトモダチシリーズ ファンタジー バタコサントソラトブマフラー`

OVAなどは『みんなのうた』に合わせてサブタイトルを`「」`でくくって付けている
今回も同様に考える
この「おともだちシリーズ」はサブタイトルが入っていないのもあり、これらはサブタイトルが分かり次第追加する

**Comment by builtinnya** [comment]
resolved by #19
