### ISSUE TITLE
汎用IMEテキスト辞書形式の読みをカタカナでなくひらがなにして欲しい

### ISSUE THREAD

**Issue by coexe** [anilogia/animedb#54]
Google日本語入力用の辞書データですが、読みをカタカナではなくひらがなにしていただけないでしょうか。
こうすることで、他のIMEでも利用できるようになり利用者が広がると思います。
汎用IMEテキスト辞書形式ではひらがな→漢字という変換データで用意するのが一般的だと私は思います。
ひらがなで記述する際、「ヴ」についてはカタカナのままで記録する(MS-IME)、「う」+「゛」で記録する(SKK/ATOK)など方言があるのですが、個人的には利用者が圧倒的に多いMS-IMEに合わせておくのがよいと考えます。(いまどきのIMEなら揺らぎがあってもちゃんと読めるはず)

**Comment by builtinnya** [comment]
ご報告ありがとうございます．
MS-IME をサポートする場合は Windows 向けということで改行コードも変える必要があるため，MS-IME 用の新しい辞書ファイル（ `dict/ms-ime-dict.txt` ）を用意することにしました．
Windows 10 でテストしたところ，エントリーが長すぎるという理由で13個ほどインポートエラーが出ますが，ご了承ください．
何か問題があれば Reopen するか新しい issue を立ててください．

**Comment by coexe** [comment]
ご対応いただきありがとうございました。
こちらではCSVから註釈情報も含めて変換して使わせていただいております。
誤字と思われる箇所を見つけた(気がする)のできちんと調べて後ほどご報告したいと思います。
https://twitter.com/coexe/status/834048161039527936
