### ISSUE TITLE
「AはB」の表記揺れについて

### ISSUE THREAD

**Issue by coexe** [anilogia/animedb#56]
「でみちゃんはかたりたい」のような
「AはB」タイプの題名のふりがな情報が
「AわB」になっているものがいくつかあるようですのでご報告します。

ねんじゅうぎょうじあにめーしょんせつぶんふくわうちおにはそと	年中行事アニメーション 節分 福は内! 鬼は外!	固有名詞	劇場版 (1987/11/6)
きっちゅにあなぜあんぜんしんわわくずれたか	キッチュニア-何故、安全神話は崩れたか?	固有名詞	OVA版 (2012/7)
しがつわきみのうそ	四月は君の嘘	固有名詞	TV版 (2014/10/8 - 2015/3/18) http://www.kimiuso.jp/
えぬえいちけーすぺしゃるあにめどきゅめんとあのひぼくらわせんじょうで	NHKスペシャル アニメドキュメント あの日、僕らは戦場で	固有名詞	TVスペシャル版 (2015/8/10) http://www.nhk.or.jp/special/detail/2015/0811/
くりいむれもんぱーとつーえすかれーしょんこんやわはーどこあ	くりいむレモン パート2 エスカレーション ～今夜はハードコア～	固有名詞	OVA版 (1984/9/10)

**Comment by builtinnya** [comment]
ご報告ありがとうございます．
修正します．
