### ISSUE TITLE
みんなのうた「(題名)」の表記揺れについて

### ISSUE THREAD

**Issue by coexe** [anilogia/animedb#57]
みんなのうた「(題名)」のふりがなが、「みんなのうた」を含むものと含まないものとがありましたのでご報告します。
個人的には「みんなのうた」を先頭に付与したほうが他のタイトルと統一感があってよいかと思いますが、どちらかに統一したほうがよいと感じました。
全部は抜き出せていませんが1つ気づいたのはここです

みんなのうたやさしいひーろー	みんなのうた「優しいヒーロー」	固有名詞	TV版 (2011/6/1)
すまいるふらわー	みんなのうた「Smileflower」	固有名詞	TV版 (2011/6/1)
おやすみ	みんなのうた「おやすみ」	固有名詞	TV版 (2011/6/1) イラスト・アニメーション
としょかんろけっと	みんなのうた「図書館ロケット」	固有名詞	TV版 (2013/10/1) http://www2.nhk.or.jp/minna/search/index.cgi?id=MIN201310_02
まわれとろいか	みんなのうた「回れトロイカ」	固有名詞	TV版 (2013/10/1) http://www2.nhk.or.jp/minna/search/index.cgi?id=MIN201310_01

**Comment by builtinnya** [comment]
ありがとうございます．
どちらに統一するか決めてから修正します．

**Comment by builtinnya** [comment]
ヨミガナに「ミンナノウタ」を含めることにします．

**現在「ミンナノウタ」がヨミガナに含まれていないもの**
- みんなのうた「りんごの木の下で」
- みんなのうた「おとうさん」
- みんなのうた「だけどI LOVE YOU」
- みんなのうた「YES, YOU」
- みんなのうた「はる なつ(ロングバージョン)」
- みんなのうた「名もない花のように」
- みんなのうた「むかしトイレがこわかった」
- みんなのうた「むし」
- みんなのうた「ラーメンどんぶり流れ唄」
- みんなのうた「おつかれさん」
- みんなのうた「ここでまた会おう」
- みんなのうた「タチツテト手を」
- みんなのうた「うじゅくじゅ?(Would you. Could you?)」
- みんなのうた「パパとあなたの影ぼうし」
- みんなのうた「YAKUSOKU ～父に送る手紙～」
- みんなのうた「優しさ」
- みんなのうた「OFF STAGE オフステージ」
- みんなのうた「おいらに惚れちゃ怪我するぜ!」
- みんなのうた「天下無敵のゴーヤーマン☆」
- みんなのうた「ぶたまんごころ」
- みんなのうた「涙のチカラ」
- みんなのうた「Happy Weekend」
- みんなのうた「ぱっぱらパパ」
- みんなのうた「プーアの森へ」
- みんなのうた「幸せきょうりゅう音頭」
- みんなのうた「くまんばちがとんできた」
- みんなのうた「Time ～時のしおり～」
- みんなのうた「テトペッテンソン」
- みんなのうた「そっくりハウス」
- みんなのうた「きょうも茶ッピーエンド」
- みんなのうた「モーニング娘。のひょっこりひょうたん島」
- みんなのうた「菜種時雨 ～natane shigure～」
- みんなのうた「ヒナのうた」
- みんなのうた「リセット」
- みんなのうた「テレビが来た日」
- みんなのうた「笑顔」
- みんなのうた「やさしい風」
- みんなのうた「ハワイアン・ロックンロール」
- みんなのうた「恋のスベスベマンジュウガニ」
- みんなのうた「哲学するマントヒヒ」
- みんなのうた「りんごのうた」
- みんなのうた「うちゅうひこうしのうた」
- みんなのうた「わきあいあい」
- みんなのうた「猫人間のあたし」
- みんなのうた「象だゾウ」
- みんなのうた「すすめ!はっくしょんベイビー」
- みんなのうた「とのさまガエル」
- みんなのうた「道」
- みんなのうた「サイボウの不思議」
- みんなのうた「フシギナチカラ」
- みんなのうた「はだかん帽」
- みんなのうた「月のワルツ」
- みんなのうた「カゼノトオリミチ」
- みんなのうた「スノウドロップ」
- みんなのうた「古いお城のものがたり」
- みんなのうた「ぬか漬けのうた」
- みんなのうた「星の世界」
- みんなのうた「レレの青い空」
- みんなのうた「涙の蕾」
- みんなのうた「トゥモロウズ ソング」
- みんなのうた「セルの恋」
- みんなのうた「夢見るジャンプ」
- みんなのうた「千の花 千の空」
- みんなのうた「クロ」
- みんなのうた「夢をかなえよう」
- みんなのうた「恋つぼみ」
- みんなのうた「チグエソ 地球の空の下で」
- みんなのうた「がんばらんば」
- みんなのうた「OSAMPO」
- みんなのうた「みんなのうみ」
- みんなのうた「花風車の森」
- みんなのうた「フンコロガシは、忙しい。」
- みんなのうた「これってホメことば?」
- みんなのうた「いらっしゃい」
- みんなのうた「ぼくはくま」
- みんなのうた「月」
- みんなのうた「私と小鳥と鈴と」
- みんなのうた「ホャホャラー」
- みんなのうた「ねっこ君」
- みんなのうた「パパとるすばん」
- みんなのうた「鳳来寺山のブッポウソウ」
- みんなのうた「おしりかじり虫」
- みんなのうた「夢人 ～ユメジン～」
- みんなのうた「おはようのうた」
- みんなのうた「ギンガムチェックの小鳥」
- みんなのうた「世界はハーモニー」
- みんなのうた「WINNER」
- みんなのうた「じーじのえてがみ ～グランドファザーズ・レター～」
- みんなのうた「なんのこれしきふろしきマン」
- みんなのうた「しあわせだいふく」
- みんなのうた「リスに恋した少年」
- みんなのうた「△□○コビッチ」
- みんなのうた「CRYSTAL CHILDREN」
- みんなのうた「光のゲンちゃん」
- みんなのうた「昆虫ニンジャ」
- みんなのうた「いつか見る虹 ～“モルダヴ”から～」
- みんなのうた「このせかいに」
- みんなのうた「べいびーろっく ～BABY ROCK～」
- みんなのうた「「手紙 ～拝啓十五の君へ～」
- みんなのうた「アロハえだまめ」
- みんなのうた「PoPo Loouise」
- みんなのうた「遠い恋の物語」
- みんなのうた「晴れ舞台」
- みんなのうた「王様のたからもの」
- みんなのうた「虹色ラブレター」
- みんなのうた「コイシテイルカ」
- みんなのうた「あなたがすき」
- みんなのうた「I'm here with you ～アイム・ヒア・ウィズ・ユー〜」
- みんなのうた「無敵のじいちゃん」
- みんなのうた「かつおぶしだよ人生は」
- みんなのうた「YELL(エール)」
- みんなのうた「ひよこぐも」
- みんなのうた「My Wish ～マイ ウィッシュ～」
- みんなのうた「天〔てん〕の川」
- みんなのうた「忍者ネギ蔵」
- みんなのうた「Aloha You～きずな～」
- みんなのうた「みならいカメレオン」
- みんなのうた「僕らのヒーロー」
- みんなのうた「えがおのはな」
- みんなのうた「ビオラは歌う」
- みんなのうた「風のブランコ」
- みんなのうた「シアワセのヨッチョレヨ!!」
- みんなのうた「きみのきもち」
- みんなのうた「フレ!フレ!大丈夫!」
- みんなのうた「ハロハログッバイ」
- みんなのうた「わらしのうた」
- みんなのうた「遠距離やろ?ウチら」
- みんなのうた「回転木馬に僕と猫」
- みんなのうた「くじらのあくび」
- みんなのうた「ピンクと呪文」
- みんなのうた「ケラケラ」
- みんなのうた「ピースフル!」
- みんなのうた「Smileflower」
- みんなのうた「おやすみ」
- みんなのうた「もういいかい」
- みんなのうた「幸せのカバン」
- みんなのうた「うたの歌」
- みんなのうた「よろしく」
- みんなのうた「なぜ」
- みんなのうた「おしりの山はエベレスト」
- みんなのうた「しじみのダンス」
- みんなのうた「ほうき星」
- みんなのうた「ヤミヤミ」
- みんなのうた「こどもしゅのうかいだん」
- みんなのうた「風をつれて」
- みんなのうた「しりとりマンボ」
- みんなのうた「ソプラノレイン」
- みんなのうた「北の風と太陽と」
- みんなのうた「ひらら恋胡蝶」
- みんなのうた「泣き虫ピエロ」
- みんなのうた「いのちの記憶」
- みんなのうた「ふきとひよこ」
- みんなのうた「ふるさと」
- みんなのうた「カタツムリ、カタオモイ」
- みんなのうた「君へのファンファーレ」
- みんなのうた「タン・タン・タン」
- みんなのうた「少年と魔法のロボット」
- みんなのうた「カチャーシ☆ブギ」
- みんなのうた「しまうまとライオン」
- みんなのうた「図書館ロケット」
- みんなのうた「回れトロイカ」
- みんなのうた「七つの海」
- みんなのうた「日々」
- みんなのうた「ビーフストロガノフ」
- みんなのうた「チョコと私」
- みんなのうた「ねむいいぬ」
- みんなのうた「おいら歌舞伎のぬらりひょん」
- みんなのうた「きみのほっぺ」
- みんなのうた「われわれは宇宙人だ!」
- みんなのうた「ムクロジの木」
- みんなのうた「スパークだ!」
- みんなのうた「お月さまと影ぼうし」
- みんなのうた「南の島のココナッツ」
