### ISSUE TITLE
その他IME辞書として使ってみて気づいた点について

### ISSUE THREAD

**Issue by coexe** [anilogia/animedb#59]
以下は仕様ということでも構わないと思っていますが気になった点についてご報告します。

1. タイトルよりも長いふりがながついているものがある
例:
なつふくのしょうじょたちひろしましょうわにじゅうねんはちがつむいか	夏服の少女たち	固有名詞	TVスペシャル版 (1988/8/7)

2. このタイトルが本当に存在しているのか不明 (OVA版とタイトルが微妙に違っておりWikipediaに載ってない)
うるせいやつらでんきじかけのおにわばん	うる星やつら 電気仕掛けのお庭番	固有名詞	劇場版 (1989)

3. CSVファイルのコメント部分に「同じのがある」「同じのある」と書かれた重複エントリが存在する
これらは機械的に抽出して確認した上で削除すべきかと思います

4. ms-ime-dict.txtがシフトJISのためタイトルが文字化けして「?」になっているものがある
BOMつきUTF-16LEかBOMつきUTF-8で収録したほうがよいのではないかと思います

以上です。たいへん便利な辞書をありがとうございました。

**Comment by builtinnya** [comment]
ご報告ありがとうございます．

1. http://www.nhk.or.jp/peace/library/program/19880807_01.html にある通り，タイトルに追記すべきですね
2. 出典であるメディア芸術データベースから引き継がれた誤りである可能性があります．https://mediaarts-db.jp/an/anime_series/2940
3. こちらもメディア芸術データベースにおいて，重複であると思われるデータに印をつけたものです．対応を決め兼ねてます
4. MS-IME 辞書は Shift JIS（CP932）しか読めないらしいのですが，いかかでしょうか．Google IME からのエクスポートもできるみたいです． http://snow-white.cocolog-nifty.com/first/2009/12/google-ms-ime-8.html

>以上です。たいへん便利な辞書をありがとうございました。

こちらこそ問題を報告していただき大変助かりました．
ありがとうございました．

**Comment by coexe** [comment]
了解しました。こちらはこれまでの報告分は全件クローズでよいと思っております。ご判断はお任せいたします。
ありがとうございました！

**Comment by coexe** [comment]
Windows 10標準のMS-IMEにて、BOMつきUTF-16LEで登録できました。BOMさえついていればUTF-8でもいけると思われます。(今回の用途だとUTF-16のほうが収納効率が良いようです)
変換は自作のツールを用いて行いました。
https://twitter.com/coexe/status/834048161039527936
![animedb_screenshot](https://cloud.githubusercontent.com/assets/566208/23225543/8994aecc-f975-11e6-8645-683da000c83c.png)

**Comment by builtinnya** [comment]
ありがとうございます．
BOM 付き UTF-8 だと読み込みに失敗したので，BOM 付き UTF-16LE でエンコードしました．
