### ISSUE TITLE
Windowsが未対応の文字(WAVE DASH等)を変更して欲しい

### ISSUE THREAD

**Issue by coexe** [anilogia/animedb#63]
アニメ作品のタイトル名部分に、Microsoft WindowsのOSの標準APIが持つCP932←→Unicodeの変換テーブルにない、通常の方法では入力できない文字が含まれているエントリが多数存在します。MS-IME用辞書データについても同様です。

現在、この問題に該当すると思われる文字は以下の通りです。

「〜」 文字U+301C
「–」 文字U+2013

	あいまいみーさーじかるふれんず	あいまいみー～Surgical Friends～
は波ダッシュにWindowsで入力可能なU+FF5Eが使われています。

	せんごくちょうじゅうぎがおつ	戦国鳥獣戯画〜乙〜
は波ダッシュにWindowsで入力できないU+301Cが使われています。

	ぴーぴんぐらいふうぃーあーざひーろー	Peeping Life – WE ARE THE HERO –
にはダッシュにWindowsで入力できないU+2013が使われています。

これは俗に言うところのWAVE DASH問題と呼ばれているものです。
……ある意味宗教論争的な不毛な話題と受け取られる可能性があることは重々承知しております。
私のようなWindowsの日本語入力IME開発者にとってはどうしても見過ごせない最重要テーマですので慎重に書きたいと思います。
しかしながらUnix利用者から見ると、この内容にはWindows利用者寄りのバイアスがかかっているということはご承知おきください。

詳細については以下の記事が詳しいです。
http://internet.watch.impress.co.jp/docs/special/691658.html
https://ja.wikipedia.org/wiki/%E3%83%80%E3%83%83%E3%82%B7%E3%83%A5_(%E8%A8%98%E5%8F%B7)

Anime DBにおいて核心となる部分を上記より引用します。
> シフトJISからUnicodeへの変換先が、２つありうるというマッピングの問題。具体的にはシフトJISで0x8160（JIS X 0208では1-33）をUnicodeに変換した場合、Microsoftの製品群ではU+FF5E、それ以外の多くはU+301Cと異なってしまう。しかも大半のフォントはU+FF5EとU+301Cのグリフを同一にしているので、外見からは全く判定できない。

実はこの問題は上記だけではありません。上の引用ではSJIS→Unicodeの変換のことにしか書かれていませんが、この問題がさらに厄介なのはこういうことです

「ほとんどのWindows利用者には、U+301CやU+2013等の文字を入力する手段がない」

なぜなら、この文字がファイル名や文書内に紛れこんでしまったら最後、MS-DOS～Windows XP時代以前の古いアプリケーション(これらは今でもWindows 10上で動作しますし、使っている人が沢山います)から利用できなくなってしまうからです。このためMSはかなり慎重にこの文字がMS-DOS時代～WindowsXP時代くらいの古いアプリケーションに渡らないよう慎重に慎重を重ねてOSの各種処理を実装しているように見えます。
文字化けは標準のメモ帳のデフォルトのセーブ設定が今でもCP932だったりするので、ちょっとメモしてセーブしただけでU+3013の波ダッシュが「?」に書き変わってしまいます。下図はこのサイトで現在配布されているms-ime-dict.txtをWindows10標準のMS-IMEに読み込ませた状態でメモ帳で変換し何度かセーブを行なった状況です。

![default](https://cloud.githubusercontent.com/assets/566208/23251985/83fda680-f9f2-11e6-8295-4ee3788b9736.png)

こうした厳しい現実を見て、「Windowsってしょうもないよね」「Unixならそんな事なんてないんだから放っておけばいいよ」で済ませるというポリシーもあることは理解しています。
しかしAnime DBのような多数の人の手による編集・改良が今後も必要となるデータにおいて、現時点で利用者が多いと思われるWindows利用者を対象とすることは開発の門戸を広げるという意味でメリットが大きいのではないかと思います。
余談になりますが、CSVの規格であるRFC4180において、改行がなぜUnixスタイルの\nではなくMS-DOSスタイルの\r\nなのか、などもこうした「開発者への門戸の広さ」を重視した結果ではないかとわたくしは考えております。

さて長々と書きましたが、この問題に対処するのは簡単です。文字を機械的に置換するだけです。ただ、どう変えるべきかについては判断が難しいかもしれません。私からは2つ提案があります。

1. 理想を言うなら、全てのU+301Cの文字をWindows利用者でも入力可能なU+FF5Eの文字側に揃えて欲しいです。これにより、Windows利用者でもこのDBの直接編集が可能となり、たくさんの開発者を受けいれる可能性が出てくると思います。
2. DB原本は現状維持とし、CSVとIME辞書データのみ変える。DB原本側のWAVE DASHはどちらの文字で記述されていても許容する。Windows側からも利用する可能性の高い、CSVファイルやIME用辞書ファイル内の文字はU+FF5E側で統一する。

何卒よろしくお願いいたします

**Comment by builtinnya** [comment]
詳細なご報告・ご提案ありがとうございました．
データベース本体 `animedb.yml` の U+301C および U+2013 を，それぞれ U+FF5E および U+002D に置換しました（当然，CSV や辞書などの生成ファイルのものも置換しました）．
対応としてはご提案していただいた 1 になります．

>「Windowsってしょうもないよね」「Unixならそんな事なんてないんだから放っておけばいいよ」で済ませるというポリシーもあることは理解しています。

>しかしAnime DBのような多数の人の手による編集・改良が今後も必要となるデータにおいて、現時点で利用者が多いと思われるWindows利用者を対象とすることは開発の門戸を広げるという意味でメリットが大きいのではないかと思います。

我々が作業する環境は macOS や GNU/Linux がメインですが，もちろんできる限り利便性を高めたい思っているので，おっしゃる通り，メリットが大きいと判断して対応いたしました．

**Comment by coexe** [comment]
ありがとうございました！
